package: feeds
version: '1.0.0-beta3'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/feeds

page:
    title: 'translate:feeds'
    perm: feeds[]
    pjax: true
    icon: rex-icon fa-rss
    subpages:
        streams:
            title: 'translate:streams'
        items:
            title: 'translate:items'
        settings:
            title: 'translate:settings'
            subpages:
                twitter:
                    title: 'translate:twitter'
                facebook:
                    title: 'translate:facebook'
                google:
                    title: 'translate:google'
                instagram:
                    title: 'translate:instagram'
        help:
            title: 'translate:help'
            perm: admin[]
            pjax: false
            subPath: README.md
            itemclass: pull-right 

requires:
    redaxo: '^5.7' 
    php:
        version: '>=7.1'

conflicts:
    packages:
        yfeed: '<1.3.0'
