package: yfeed
version: '1.3.0'
author: Gregor Harlan, Thomas Blum
supportpage: www.redaxo.org/de/forum/

page:
    title: 'translate:yfeed'
    perm: yfeed[]
    pjax: true
    icon: rex-icon fa-rss
    subpages:
        streams:
            title: 'translate:streams'
        items:
            title: 'translate:items'
        settings:
            title: 'translate:settings'
            subpages:
                twitter:
                    title: 'translate:twitter'
                facebook:
                    title: 'translate:facebook'
                google:
                    title: 'translate:google'
                instagram:
                    title: 'translate:instagram'
        help:
            title: 'translate:help'
            perm: admin[]
            pjax: false
            subPath: README.md
            itemclass: pull-right 
